config/routes.rb
Rails.application.routes.draw do
  get 'orders/success'
  get 'orders/bought'
  get 'orders/sold'
  resources :listings
  devise_for :users
  root 'pages#home'

  post "listings/:id/order", to: "listings#place_order", as: "place_order"

  get 'orders/success', to: 'orders#success'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_rich_text :description
  has_one_attached :picture


  enum condition: {
    Nothing_but_bones: 1,
    Only_good_for_parts: 2,
    Needs_a_ground_up_repair: 3,
    Mechanically_fine_but_needs_full_body_work: 4,
    Body_is_fine_but_needs_major_mechanical_work: 5,
    Someone_with_spanners_could_fix_it: 6
  }

  
# failed attempts at drop down boxes

#   enum state: {
#     Queensland: 1,
#     New_South_Wales: 2,
#     Victoria: 3,
#     Tasmania: 4,
#     South_Australia: 5,
#     Northern_Territory: 6,
#     Western_Australia: 7,
#     Australian_Capital_Territory: 8
# }

#   enum bodytype: {
#     Coupe: 1,
#     Hatch: 2,
#     Light_Truck: 3,
#     Sedan: 4,
#     Ute: 5,
#     Van: 6,
#     Wagon: 7,
#     Other: 8
#   }

    # enum seat: {
    #   One: 1,
    #   Two: 2,
    #   Three: 3,
    #   Four: 4,
    #   Five: 5,
    #   Six: 6,
    #   Seven: 7,
    #   Eight: 8
    # }
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :listing
  belongs_to :buyer, foreign_key: "buyer_id", class_name: "User"
  belongs_to :seller, foreign_key: "seller_id", class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
       
  has_many :listings

  has_many :sold_orders, foreign_key: "seller_id", class_name: "Order"
  has_many :bought_orders, foreign_key: "buyer_id", class_name: "Order"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: %i[ show edit update destroy place_order ]
  before_action :set_form_vars, only: %i[ new edit]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :authorize_user, only: [:edit, :update, :destroy]


  # GET /listings or /listings.json
  def index
    @listings = Listing.all
  end

  # GET /listings/1 or /listings/1.json
  def show
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings or /listings.json
  def create
    @listing = Listing.new(listing_params)
    @listing.user = current_user

    respond_to do |format|
      if @listing.save
        format.html { redirect_to listing_url(@listing), notice: "Listing was successfully created." }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1 or /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to listing_url(@listing), notice: "Listing was successfully updated." }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1 or /listings/1.json
  def destroy
    @listing.destroy

    respond_to do |format|
      format.html { redirect_to listings_url, notice: "Listing was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def place_order
    Order.create(
      listing_id: @listing.id,
      seller_id: @listing.user_id,
      buyer_id: current_user.id
    )

    @listing.update(sold: true)

    redirect_to orders_success_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    def set_form_vars
      @categories = Category.all
      @conditions = Listing.conditions.keys
      # @states = Listing.states.keys
      # @bodytypes = Listing.bodytypes.keys
      # @seats = Listing.seats.keys
    end

    def  authorize_user
      if @listing.user_id != current_user.id
        flash[:alert] = "You can't do that!"
        redirect_to listings_path
      end
    end

    # Only allow a list of trusted parameters through.
    def listing_params
      params.require(:listing).permit(:year, :month, :manufacturer, :model, :bodytype, :state, :odometer, :colour, :condition, :seats, :doors, :sold, :price, :description, :user_id, :category_id, :picture)
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!
  
  def success
  end

  def bought
    @bought_items = current_user.bought_orders
  end

  def sold
    @sold_items = current_user.sold_orders
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def success
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
    def format_condition(condition)
        words = condition.split("_").map do |word| 
            word.capitalize
        end
        words.join(" ")
    end


    
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Revonate</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/nav' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>

    <%# <% if Rails.env.development? %>
      <%# <% console %>
    <%# <% end %> 
     
  </body>
</html>

app/views/listings/_form.html.erb
<%= form_with(model: listing) do |form| %>
  <% if listing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

      <ul>
        <% listing.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :category_id %>
    <%= form.select :category_id, @categories.map {|c| [c.name, c.id]} %>
  </div>

  <div class="field">
    <%= form.label :condition %>
    <%= form.select :condition, options_for_select(Listing.conditions.map {|key, value| 
    [key.titleize, Listing.conditions.key(value)]}, @listing.condition) %>
  </div>

  <div class="field">
    <%= form.label :state %>
    <%= form.text_field :state %>
  </div>

  <div class="field">
    <%= form.label :bodytype %>
    <%= form.text_field :bodytype %>
  </div>

  <div class="field">
    <%= form.label :year %>
    <%= form.number_field :year %>
  </div>

  <div class="field">
    <%= form.label :month %>
    <%= form.text_field :month %>
  </div>

  <div class="field">
    <%= form.label :picture %>
    <%= form.file_field :picture, accept: "image/png, image/jpg, image/jpeg" %>
  </div>

  <div class="field">
    <%= form.label :manufacturer %>
    <%= form.text_field :manufacturer %>
  </div>

  <div class="field">
    <%= form.label :model %>
    <%= form.text_field :model %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.rich_text_area :description %>
  </div>
  
  <div class="field">
    <%= form.label :odometer %>
    <%= form.number_field :odometer %>
  </div>

  <div class="field">
    <%= form.label :colour %>
    <%= form.text_field :colour %>
  </div>

  <div class="field">
    <%= form.label :seats %>
    <%= form.number_field :seats %>
  </div>

  <div class="field">
    <%= form.label :doors %>
    <%= form.number_field :doors %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>
  
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/listings/edit.html.erb
<h1>Editing Listing</h1>

<%= render 'form', listing: @listing %>

<%= link_to 'Show', @listing %> |
<%= link_to 'Back', listings_path %>

app/views/listings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listings</h1>

<table>
  <thead>
    <tr>
      <th>Year</th>
      <th>Manufacturer</th>
      <th>Model</th>
      <th>State</th>
      <th>Condition</th>
      <th>Sold</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @listings.each do |listing| %>
      <tr>
        <td><%= listing.year %></td>
        <td><%= listing.manufacturer %></td>
        <td><%= listing.model %></td>
        <td><%= listing.state %></td>
        <td><%= format_condition(listing.condition)  %></td>
        <td><%= listing.sold %></td>
        <td><%= listing.price %></td>
        
        
        <td><%= link_to 'Show', listing %></td>
        <% if  current_user && current_user.id == listing.user.id %>
          <td><%= link_to 'Edit', edit_listing_path(listing) %></td>
          <td><%= link_to 'Destroy', listing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Listing', new_listing_path %>

app/views/listings/new.html.erb
<h1>New Listing</h1>

<%= render 'form', listing: @listing %>

<%= link_to 'Back', listings_path %>

app/views/listings/show.html.erb
<p id="notice"><%= notice %></p>

<div>
<% if @listing.picture.attached?%>
  <%= image_tag @listing.picture, alt: @listing.model %>
<% else %>
  <%= image_tag "http://www.placecage.com/640/360", alt: @listing.model %>
<% end %>
</div>


<% if @listing.sold %>
  <h3>SOLD</h3>
<% elsif current_user && current_user.id == @listing.user_id %>
  <h3> This vehicle is currently for sale </h3>
<% elsif current_user %>
  <%= button_to "Buy now!", place_order_path %>
<% else %>
  <h3> Please Log in to make a purchase </h3>
 <% end %>

<p>
  <strong>Year:</strong>
  <%= @listing.year %>
</p>

<p>
  <strong>Month:</strong>
  <%= @listing.month %>
</p>

<p>
  <strong>Manufacturer:</strong>
  <%= @listing.manufacturer %>
</p>

<p>
  <strong>Model:</strong>
  <%= @listing.model %>
</p>

<p>
  <strong>Bodytype:</strong>
  <%= @listing.bodytype %>
</p>

<p>
  <strong>State:</strong>
  <%= @listing.state %>
</p>

<p>
  <strong>Odometer:</strong>
  <%= @listing.odometer %>
</p>

<p>
  <strong>Colour:</strong>
  <%= @listing.colour %>
</p>

<p>
  <strong>Condition:</strong>
  <%= format_condition(@listing.condition) %>
</p>

<p>
  <strong>Seats:</strong>
  <%= @listing.seats %>
</p>

<p>
  <strong>Doors:</strong>
  <%= @listing.doors %>
</p>

<p>
  <strong>Sold:</strong>
  <%= @listing.sold %>
</p>

<p>
  <strong>Price:</strong>
  <%= @listing.price %>
</p>

<p>
  <strong>Description:</strong>
  <%= @listing.description %>
</p>

<p>
  <strong>User:</strong>
  <%= @listing.user_id %>
</p>

<p>
  <strong>Category:</strong>
  <%= @listing.category_id %>
</p>

<% if current_user && current_user.id == @listing.user.id %>
  <%= link_to 'Edit', edit_listing_path(@listing) %> |
  <% end %>

<%= link_to 'Back', listings_path %>

app/views/orders/bought.html.erb
<h1>Vehicles you have purchased</h1>


<table>
  <thead>
    <tr>
      <th>Year</th>
      <th>Manufacturer</th>
      <th>Model</th>
      <th>State</th>
      <th>Condition</th>
      <th>Price</th>
      <th>Seller</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bought_items.each do |item| %>
      <tr>
        <td><%= item.listing.year %></td>
        <td><%= item.listing.manufacturer %></td>
        <td><%= item.listing.model %></td>
        <td><%= item.listing.state %></td>
        <td><%= format_condition(item.listing.condition) %></td>
        <td><%= item.listing.price %></td>
        <td><%= item.seller.username %></td> 
        <td><%= link_to 'Show', item.listing %> </td>
      <tr>
    <% end %>
  <tbody>
</table>

app/views/orders/sold.html.erb
<h1>Vehicles you have sold</h1>


<table>
  <thead>
    <tr>
      <th>Year</th>
      <th>Manufacturer</th>
      <th>Model</th>
      <th>State</th>
      <th>Condition</th>
      <th>Price</th>
      <th>Seller</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sold_items.each do |item| %>
      <tr>
        <td><%= item.listing.year %></td>
        <td><%= item.listing.manufacturer %></td>
        <td><%= item.listing.model %></td>
        <td><%= item.listing.state %></td>
        <td><%= format_condition(item.listing.condition) %></td>
        <td><%= item.listing.price %></td>
        <td><%= item.seller.username %></td> 
        <td><%= link_to 'Show', item.listing %></td>
      <tr>
    <% end %>
  <tbody>
</table>

app/views/orders/success.html.erb
<h1>Woohoo thanks for your order!</h1>

app/views/pages/home.html.erb
<h1>Welcome to REVonate!!</h1>


<p> Your one stop shop for all value-adding car projects </p>

app/views/shared/_nav.html.erb
 <%= link_to "Home", root_path, class: "button button-primary" %>
 <%= link_to "Listings", listings_path, class: "button button"  %>

<span>
<%= link_to "Bought Items", orders_bought_path, class: "button button" %>
<%= link_to "Sold Items", orders_sold_path, class: "button button" %>
</span>

<span style="float:right">
  <% if user_signed_in? %>
   <%= link_to "Sign out",destroy_user_session_path, method: :delete, class: "button button-primary" %>
  <% else  %>
      <%= link_to "Sign up", new_user_registration_path, class: "button button-primary"  %>
      <%= link_to "Sign in", new_user_session_path, class: "button button-primary"  %>
  <% end %>
</span>